// <auto-generated />
using System;
using Hoc_Lieu_Va_Review_Demooo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoc_Lieu_Va_Review_Demooo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.BaoCao", b =>
                {
                    b.Property<int>("BaoCaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaoCaoID"));

                    b.Property<int?>("BinhLuanID")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int?>("TaiLieuID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("BaoCaoID");

                    b.HasIndex("BinhLuanID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("TaiLieuID");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.BinhLuan", b =>
                {
                    b.Property<int>("BinhLuanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinhLuanID"));

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int?>("TaiLieuID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("BinhLuanID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("TaiLieuID");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.HocPhan", b =>
                {
                    b.Property<int>("HocPhanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocPhanID"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NganhID")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HocPhanID");

                    b.HasIndex("NganhID");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Khoa", b =>
                {
                    b.Property<int>("KhoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaID"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KhoaID");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Nganh", b =>
                {
                    b.Property<int>("NganhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NganhID"));

                    b.Property<int>("KhoaID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NganhID");

                    b.HasIndex("KhoaID");

                    b.ToTable("Nganh");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("HocPhanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReviewID");

                    b.HasIndex("HocPhanID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.TaiLieu", b =>
                {
                    b.Property<int>("TaiLieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiLieuID"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HocPhanID")
                        .HasColumnType("int");

                    b.Property<double>("KichThuoc")
                        .HasColumnType("float");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LuotTai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("TaiLieuID");

                    b.HasIndex("HocPhanID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.BaoCao", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.BinhLuan", "BinhLuan")
                        .WithMany()
                        .HasForeignKey("BinhLuanID");

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewID");

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.TaiLieu", "TaiLieu")
                        .WithMany()
                        .HasForeignKey("TaiLieuID");

                    b.Navigation("BinhLuan");

                    b.Navigation("NguoiDung");

                    b.Navigation("Review");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.BinhLuan", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.BinhLuan", "ParentBinhLuan")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewID");

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.TaiLieu", "TaiLieu")
                        .WithMany()
                        .HasForeignKey("TaiLieuID");

                    b.Navigation("NguoiDung");

                    b.Navigation("ParentBinhLuan");

                    b.Navigation("Review");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.HocPhan", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.Nganh", "Nganh")
                        .WithMany("HocPhans")
                        .HasForeignKey("NganhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Nganh", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.Khoa", "Khoa")
                        .WithMany("Nganhs")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Review", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("HocPhanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.TaiLieu", b =>
                {
                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("HocPhanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoc_Lieu_Va_Review_Demooo.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Khoa", b =>
                {
                    b.Navigation("Nganhs");
                });

            modelBuilder.Entity("Hoc_Lieu_Va_Review_Demooo.Models.Nganh", b =>
                {
                    b.Navigation("HocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
